### ISSUE TITLE
Would it be too much to INCLUDE a two-for solution in this repo?

### ISSUE THREAD

**Issue by joshgoebel** [exercism/javascript-test-runner#18]
That way someone can easily "test" the test runner without needing any external dependencies?

**Comment by SleeplessByte** [comment]
https://github.com/exercism/javascript-analyzer/tree/master/test/fixtures/two-fer can copy this folder.

**Comment by joshgoebel** [comment]
Is that saying "use this instead" or is it an answer to my actual question?  The goal:

- someone downloads test runner
- they can immediately hack/test it with local two-fer that comes "buiilt-in"

**Comment by SleeplessByte** [comment]
Fixed by #26
