### ISSUE TITLE
The test throws this error but the answer works fine locally.

### ISSUE THREAD

**Issue by vccddd** [exercism/javascript-test-runner#696]
<img width="370" alt="image" src="https://github.com/exercism/javascript-test-runner/assets/46776513/3c54df80-8e37-4f56-8fd4-17ae1864d3e0">

There is still an error when I copied a correct answer from another solution.

**Comment by SleeplessByte** [comment]
Please follow http://forum.exercism.org/t/js-an-error-occurred/6054/2
